// Errors
export const GET_ERRORS = "GET_ERRORS";
// WebHook
export const GET_WEBHOOK = "GET_WEBHOOK";
export const DELETE_WEBHOOK = "DELETE_WEBHOOK";
export const GET_WEBHOOKS = "GET_WEBHOOKS";
// User
export const SET_CURRENT_USER = "SET_CURRENT_USER";
// COVID and AIR Select input
export const GET_COVID_OR_AIR_SELECT_COUNTRIES = "GET_COVID_OR_AIR_SELECT_COUNTRIES"
// AIR Select input
export const GET_AIR_SELECT_REGION = "GET_AIR_SELECT_REGION"
export const GET_AIR_SELECT_CITY = "GET_AIR_SELECT_CITY"
